#
# Makefile - top level make for fabooh examples
#
# common.mk is used to select MCU and BOARD variants
#


.PHONY: all clean install

all:
	@make -C gdb_bootloader all

clean:
	@make -C gdb_bootloader clean
	
install:
	@make -C gdb_bootloader install
